### ISSUE TITLE
(Possibly) broken code gen

### ISSUE THREAD

**Issue by huntwj** [gcanti/fp-ts-codegen#16]
The following code results in a non-error state, but the produced code does not compile:

```
data Auth U T = NotAuth | Authorized { user :: U, data :: T }
```
Then check `fp-ts encoding`.

The generic types introduced by the fp-ts encoding do not match the given type parameters. I'm new enough to all this to be open to the idea that the issue is with me, but just in case... :)

The given TypeScript errors are:

```
Cannot find name 'A'. ts(2304) [16, 17]
Cannot find name 'L'. ts(2304) [17, 17]
Cannot find name 'A'. ts(2304) [30, 17]
Cannot find name 'L'. ts(2304) [31, 17]
```

Here you go! ;)

**Comment by gcanti** [comment]
@huntwj thanks for the bug report
